---
- name: Copy the Node Exporter systemd service file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    owner: root
    group: root
    mode: 0644
  notify: restart node_exporter
  when: ansible_service_mgr == 'systemd'

- name: "Ensure Node Exporter log file ({{ _node_exporter_log_file }}) exists and has the correct permissions"
  file:
    path: "{{ _node_exporter_log_file }}"
    state: touch
    mode: u+rw,g-wx,o-
    modification_time: preserve
    access_time: preserve
    owner: "{{ _node_exporter_system_group }}"
    group: "{{ _node_exporter_system_user }}"

- name: Copy the Node Exporter upstart service file
  template:
    src: node_exporter.j2
    dest: /etc/init.d/node_exporter
    owner: root
    group: root
    mode: 0755
  notify: restart node_exporter
  when: ansible_service_mgr == 'upstart'
  
- name: "Create textfile collector dir ({{ node_exporter_textfile_dir }})"
  file:
    path: "{{ node_exporter_textfile_dir }}"
    state: directory
    owner: "{{ node_exporter_textfile_dir_user }}"
    group: "{{ node_exporter_textfile_dir_group }}"
    recurse: true
    mode: "{{ node_exporter_textfile_dir_access }}"
  when: node_exporter_textfile_dir | length > 0

- name: Allow Node Exporter port in SELinux on RedHat OS family
  seport:
    ports: "{{ node_exporter_web_listen_address.split(':')[-1] }}"
    proto: tcp
    setype: http_port_t
    state: present
  when:
    - ansible_version.full is version_compare('2.4', '>=')
    - ansible_selinux.status == "enabled"
